name: リリースを作成する

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
      - name: Po
        run: echo $(ls)
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build.sh
            gh-build/windows/filversish.exe